"""持久任务恢复、租户生命周期、文件路径、指标与本地性能抽样。"""
from http_client import Client
import unittest,urllib.request,urllib.error,json,uuid,time,subprocess,pathlib,os,statistics,zipfile,io
BASE='http://localhost:8081'
TAG='OPS'+uuid.uuid4().hex[:8]
def sql(query):
 r=subprocess.run(['docker','compose','exec','-T','db','psql','-U','mdm','-d','mdm_test','-At','-v','ON_ERROR_STOP=1','-c',query],capture_output=True,text=True,check=True);return r.stdout.strip()
def upload(c,path,fields,name,content):
 boundary=uuid.uuid4().hex;parts=[]
 for k,v in fields.items():parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="{k}"\r\n\r\n{v}\r\n'.encode())
 parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{name}"\r\nContent-Type: application/octet-stream\r\n\r\n'.encode()+content+b'\r\n');parts.append(f'--{boundary}--\r\n'.encode())
 req=urllib.request.Request(BASE+'/api/v1'+path,data=b''.join(parts),headers={'X-Tenant-Code':c.tenant,'Idempotency-Key':uuid.uuid4().hex,'Content-Type':'multipart/form-data; boundary='+boundary},method='POST')
 return json.load(c.opener.open(req))
def restart():
 pid=int(pathlib.Path('.runtime/test-backend.pid').read_text());os.kill(pid,15)
 for _ in range(100):
  try:urllib.request.urlopen(BASE+'/actuator/health',timeout=.2);time.sleep(.05)
  except Exception:break
 jars=sorted(pathlib.Path('.runtime').glob('test-app-*.jar'),key=lambda p:p.stat().st_mtime);env=dict(os.environ);env.update(PORT='8081',DATABASE_URL='jdbc:postgresql://localhost:5432/mdm_test',RETRY_DELAYS='1,1,1,1',WORKER_DELAY='100',JAVA_HOME='/workspace/.tools/jdk-21.0.6+7')
 with open('.runtime/test-backend.log','ab') as f:p=subprocess.Popen([env['JAVA_HOME']+'/bin/java','-jar',str(jars[-1].resolve())],stdout=f,stderr=f,env=env,start_new_session=True)
 pathlib.Path('.runtime/test-backend.pid').write_text(str(p.pid))
 for _ in range(100):
  try:urllib.request.urlopen(BASE+'/actuator/health',timeout=.5);return
  except Exception:time.sleep(.1)
 raise AssertionError('测试实例未恢复')
class Operations(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.e=Client('editor','TENANT-B',BASE);cls.r=Client('reviewer','TENANT-B',BASE);cls.a=Client('admin','TENANT-B',BASE);cls.s=cls.e.call('/categories/GLASS_CLOTH/schema');cls.evidence=[]
 def job(self,n=1):
  csv='materialName,model,width,basisWeight,manufacturer\n'+''.join(f'{TAG}{i},{TAG}{uuid.uuid4().hex[:8]},1270,210,SUP-001\n' for i in range(n))
  f=upload(self.e,'/import-files',{'categoryCode':'GLASS_CLOTH'},TAG+'.csv',csv.encode())
  mapping={k:('materialName' if k=='materialName' else {'target':'attributes.'+k,'unit':{'width':'mm','basisWeight':'g/m2'}.get(k,'')}) for k in ['materialName','model','width','basisWeight','manufacturer']}
  return self.e.call('/import-jobs','POST',{'fileId':f['fileId'],'categoryCode':'GLASS_CLOTH','schemaVersionId':self.s['id'],'sheet':'CSV','mapping':mapping},expected=202)
 def wait(self,j,status):
  for _ in range(500):
   x=self.e.call('/import-jobs/'+j['id'])
   if x['status']==status:return x
   time.sleep(.03)
  self.fail(str(x))
 def test_01_precheckPauseRestartResume(self):
  j=self.job(200);before=sql('select count(*) from material; select count(*) from outbox_event; select count(*) from number_sequence;')
  j=self.e.call('/import-jobs/'+j['id']+'/validate','POST',{},j['rowVersion']);j=self.wait(j,'READY');self.assertEqual(before,sql('select count(*) from material; select count(*) from outbox_event; select count(*) from number_sequence;'))
  j=self.e.call('/import-jobs/'+j['id']+'/commit','POST',{'onlyPassed':True},j['rowVersion'])
  # Pause through the API while the durable worker is running.
  for _ in range(100):
   j=self.e.call('/import-jobs/'+j['id'])
   if any(r['state']=='SUCCEEDED' for r in j['rows']):break
   time.sleep(.01)
  j=self.e.call('/import-jobs/'+j['id']+'/pause','POST',{'reason':'重启恢复验收'},j['rowVersion']);saved={r['rowNo']:r['materialId'] for r in j['rows'] if r['state']=='SUCCEEDED'};self.assertGreater(len(saved),0)
  t=self.a.call('/platform/tenants');t=next(t for t in t if t['code']=='TENANT-B');t=self.a.call('/platform/tenants/'+t['id']+'/suspend','POST',{'reason':'暂停恢复验收'},t['rowVersion']);self.e.call('/materials','POST',{},expected=409);restart();self.__class__.e=Client('editor','TENANT-B',BASE);self.__class__.r=Client('reviewer','TENANT-B',BASE);self.__class__.a=Client('admin','TENANT-B',BASE)
  self.assertEqual('PAUSED',self.e.call('/import-jobs/'+j['id'])['status']);self.a.call('/platform/tenants/'+t['id']+'/resume','POST',{'reason':'恢复验收'},t['rowVersion']);j=self.e.call('/import-jobs/'+j['id']);self.e.call('/import-jobs/'+j['id']+'/resume','POST',{},j['rowVersion']);j=self.wait(j,'COMPLETED');self.assertEqual(200,sum(r['state']=='SUCCEEDED' for r in j['rows']));self.assertEqual(200,len(set(r['materialId'] for r in j['rows'])));self.assertTrue(all(saved[r['rowNo']]==r['materialId'] for r in j['rows'] if r['rowNo'] in saved));self.evidence.append({'importRestartRows':200,'successfulRowsBeforeRestart':len(saved),'replayed':0})
 def test_02_exportXlsxAndFileTenantScope(self):
  f=self.e.call('/materials/export','POST',{'query':{'categoryCode':'GLASS_CLOTH','name':TAG},'format':'XLSX'});data=self.e.call('/files/'+f['id']);z=zipfile.ZipFile(io.BytesIO(data));self.assertIn('xl/worksheets/sheet1.xml',z.namelist());u=upload(self.e,'/import-files',{'categoryCode':'GLASS_CLOTH'},'回读.xlsx',data);self.assertEqual(['物料'],u['sheets']);p=self.e.call('/import-files/'+u['fileId']+'/preview','POST',{'sheet':'物料'});self.assertEqual(f['rowCount'],p['rowCount']);other=Client('editor','TENANT-A',BASE);other.call('/files/'+f['id'],expected=404);reader=Client('reader','TENANT-B',BASE);reader.call('/files/'+f['id'],expected=403);self.evidence.append({'xlsxExportAndReadRows':p['rowCount'],'crossTenantFileDenied':True})
 def test_03_archiveReopenAndMembers(self):
  uid=self.e.call('/tenants/current')['user']['id'];t=self.a.call('/platform/tenants','POST',{'code':TAG,'name':'归档验收租户','adminUserId':uid});t=self.a.call('/platform/tenants/'+t['id']+'/activate','POST',{'reason':'启用'},t['rowVersion']);t=self.a.call('/platform/tenants/'+t['id']+'/archive','POST',{'reason':'空任务归档'},t['rowVersion']);t=self.a.call('/platform/tenants/'+t['id']+'/reopen','POST',{'reason':'重开'},t['rowVersion']);self.assertEqual('SUSPENDED',t['status']);t=self.a.call('/platform/tenants/'+t['id']+'/resume','POST',{'reason':'恢复'},t['rowVersion']);own=Client('editor',TAG,BASE);self.assertIn('ADMIN',own.call('/tenants/current')['actions']);self.assertNotIn('CREATE',own.call('/tenants/current')['actions']);self.assertEqual(0,own.call('/dashboard')['materials']);self.evidence.append({'archiveReopen':'ACTIVE','sameUserDifferentTenantRoles':True})
 def test_04_fileOutboxInboxAndClient(self):
  uid=self.e.call('/tenants/current')['user']['id'];key=uuid.uuid4().hex;cfg={'transport':'FILE','url':'http://localhost:9091/targets/'+TAG+'/materials','healthUrl':'http://localhost:9091/health','contractTestUrl':'http://localhost:9091/targets/'+TAG+'/validate','inboundUserId':uid};s=self.e.call('/integration-systems','POST',{'code':TAG,'name':'文件集成验收','config':cfg,'clientKey':key});m=self.e.call('/integration-systems/'+s['id']+'/mappings','POST',{'config':{'fields':[{'source':'materialNo','target':'ITEM_CODE','required':True}],'policies':{'materialName':'REVIEW'}}});self.e.call('/mappings/'+m['id']+'/publish','POST',{},m['rowVersion']);self.e.call('/integration-systems/'+s['id']+'/test','POST',{});s=self.e.call('/integration-systems/'+s['id']);self.e.call('/integration-systems/'+s['id'],'PATCH',{'active':True,'paused':True},s['rowVersion'])
  body={'schemaVersionId':self.s['id'],'materialName':TAG+'FILE','attributes':{'model':TAG+'FILE','width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001'}}};asset=self.e.call('/materials','POST',body,expected=201);r=self.e.call('/materials/'+asset['id']+'/change-requests','POST',{'kind':'NEW'},asset['rowVersion']);r=self.e.call('/requests/'+r['id']+'/submit','POST',{},r['rowVersion']);self.r.call('/requests/'+r['id']+'/approve','POST',{},r['rowVersion']);restart();self.__class__.e=Client('editor','TENANT-B',BASE);self.__class__.r=Client('reviewer','TENANT-B',BASE);self.__class__.a=Client('admin','TENANT-B',BASE);s=self.e.call('/integration-systems/'+s['id']);self.e.call('/integration-systems/'+s['id'],'PATCH',{'paused':False},s['rowVersion'])
  for _ in range(200):
   ds=[x for x in self.e.call('/deliveries') if x['systemId']==s['id'] and x['materialId']==asset['id']]
   if ds and ds[0]['state']=='WAIT_CONFIRMATION':break
   time.sleep(.05)
  d=self.e.call('/deliveries/'+ds[0]['id']);content=self.e.call('/files/'+d['file']['id']);event=content if isinstance(content,dict) else json.loads(content);self.assertEqual(asset['id'],event['event']['aggregate']['id']);self.e.call('/deliveries/'+d['id']+'/confirm','POST',{'success':True,'externalId':TAG+'-EXTERNAL','reason':'文件接收端回执确认'});self.assertEqual('SUCCEEDED',self.e.call('/deliveries/'+d['id'])['state'])
  msg={'sourceMessageId':TAG+'IN','externalId':TAG+'IN','categoryCode':'GLASS_CLOTH','data':{**body,'materialName':TAG+'IN','attributes':{**body['attributes'],'model':TAG+'IN'}}};msg['data'].pop('schemaVersionId');f=upload(self.e,'/integration-files',{'systemId':s['id']},'入站.jsonl',(json.dumps(msg)+'\n{"bad":true}\n'+json.dumps(msg)+'\n').encode());self.assertEqual(3,f['rowCount']);self.assertEqual(f['results'][0]['result']['materialId'],f['results'][2]['result']['materialId']);self.assertEqual('INBOUND_IDENTITY',f['results'][1]['code']);req=urllib.request.Request(BASE+'/api/v1/inbound/'+s['id'],data=json.dumps(msg).encode(),headers={'Content-Type':'application/json','X-Integration-Key':key},method='POST');self.assertEqual(f['results'][0]['result']['materialId'],json.load(urllib.request.urlopen(req))['materialId']);self.evidence.append({'outboxProcessRestart':'WAIT_CONFIRMATION→SUCCEEDED','fileBatchRows':3,'duplicateIncomingCreates':0})
 def test_05_metricsTraceAndLatency(self):
  samples={};items=self.e.call('/materials/search','POST',{'categoryCode':'GLASS_CLOTH','name':TAG})['items'];mid=items[0]['id'];body={'materialName':'性能预览','schemaVersionId':self.s['id'],'attributes':{'model':'PERF','width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001'}}}
  for name,path,method,b in [('detail','/materials/'+mid,'GET',None),('query','/materials/search','POST',{'categoryCode':'GLASS_CLOTH','name':TAG}),('preview','/material-numbers:preview','POST',body)]:
   times=[]
   for _ in range(100):
    start=time.perf_counter();self.e.call(path,method,b);times.append((time.perf_counter()-start)*1000)
   samples[name]={'requests':100,'p95Ms':round(sorted(times)[94],2),'concurrency':1}
  dashboard=self.e.call('/dashboard');self.assertNotEqual('未采集',dashboard['apiLatencyP95']);self.assertGreater(len(self.e.call('/operation-logs?objectId='+mid)),0);self.evidence.append({'latencySample':samples,'materialRows':sql('select count(*) from material;'),'cpu':os.cpu_count(),'metricDashboard':dashboard['apiLatencyP95']})
 def test_06_backgroundExport(self):
  f=self.e.call('/materials/export','POST',{'query':{'categoryCode':'GLASS_CLOTH'},'format':'CSV'})
  self.assertEqual('PENDING',f['status'])
  for _ in range(200):
   j=self.e.call('/export-jobs/'+f['id'])
   if j['status'] in ('COMPLETED','FAILED'):break
   time.sleep(.05)
  self.assertEqual('COMPLETED',j['status']);self.assertGreater(len(self.e.call('/files/'+j['fileId'])),1000);self.evidence.append({'backgroundExport':'COMPLETED','queryCutoff':j['config']['query']['cutoff']})
 def test_07_metadataSnapshotsLegacyAndIdentityConflict(self):
  s=self.s;meta=self.e.call('/metadata');dictionary=next(x for x in meta if x['kind']=='DICTIONARY' and x['code']=='PRECISION');bearing=self.e.call('/categories/BEARING/schema');original=bearing['bundle']['attributes'][3]['options'];changed={**dictionary['data']};changed['items']=[{'code':'P0','label':'新释义','active':False}];self.e.call('/metadata','POST',{'kind':'DICTIONARY','code':'PRECISION','data':changed});self.assertEqual(original,self.e.call('/schemas/'+bearing['id'])['bundle']['attributes'][3]['options'])
  attrs={'model':TAG+'OLD','width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001'}};no='GC-'+TAG+'OLD-1270-HONGHE';before=sql('select count(*) from material;');p=self.e.call('/material-numbers:parse','POST',{'materialNo':no,'parseRuleVersionId':s['id']});self.assertEqual('EXACT_SYNTAX',p['matchType']);self.assertEqual(before,sql('select count(*) from material;'));self.e.call('/material-numbers:parse','POST',{'materialNo':no},expected=422)
  body={'schemaVersionId':s['id'],'materialName':TAG+'历史','numberSource':'LEGACY','legacyNo':no,'sourceEvidence':'历史清单第1行','parseRuleVersionId':s['id'],'attributes':attrs};m=self.e.call('/materials','POST',body,expected=201);r=self.e.call('/materials/'+m['id']+'/change-requests','POST',{'kind':'NEW'},m['rowVersion']);r=self.e.call('/requests/'+r['id']+'/submit','POST',{},r['rowVersion']);self.r.call('/requests/'+r['id']+'/approve','POST',{},r['rowVersion']);m=self.e.call('/materials/'+m['id']);self.assertEqual(no,m['materialNo']);self.assertIsNone(m['codeRuleVersionId']);self.assertEqual(s['id'],m['parseRuleVersionId']);copy=self.e.call('/materials/'+m['id']+'/copy','POST',{});self.assertEqual('GENERATED',copy['numberSource']);self.assertIsNone(copy['materialNo']);self.assertEqual([],copy['identities'] if 'identities' in copy else [])
  system=next(x for x in self.e.call('/integration-systems') if x['code']=='ERP-A');binding={'externalId':TAG+'CONFLICT','materialId':m['id'],'reason':'外部身份验证'};self.e.call('/integration-systems/'+system['id']+'/identities','POST',binding);self.e.call('/integration-systems/'+system['id']+'/identities','POST',{**binding,'materialId':copy['id']},expected=409);self.evidence.append({'metadataSnapshot':'unchanged','legacyParseVersion':'actual','generatedVersion':None,'externalIdConflict':'blocked'})
 def test_08_postgresSkipLockedAndTenantForeignKeys(self):
  one=self.job(1);two=self.job(1);ids=[one['id'],two['id']];query="begin;select id from import_job where id in ('"+ids[0]+"','"+ids[1]+"') order by id for update skip locked limit 1;select pg_sleep(1);commit;"
  cmd=['docker','compose','exec','-T','db','psql','-U','mdm','-d','mdm_test','-At','-v','ON_ERROR_STOP=1','-c',query]
  first=subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True);time.sleep(.1);second=subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True);a=first.communicate(timeout=5)[0];b=second.communicate(timeout=5)[0];self.assertEqual(0,first.returncode);self.assertEqual(0,second.returncode);claimed=[next(x for x in out.splitlines() if x in ids) for out in [a,b]];self.assertEqual(2,len(set(claimed)))
  other=Client('editor','TENANT-A',BASE);f=upload(other,'/import-files',{'categoryCode':'GLASS_CLOTH'},'隔离.csv',b'materialName,model\nA,A\n');query="begin;update import_job set file_id='"+f['fileId']+"' where id='"+one['id']+"';rollback;";r=subprocess.run(['docker','compose','exec','-T','db','psql','-U','mdm','-d','mdm_test','-v','ON_ERROR_STOP=1','-c',query],capture_output=True,text=True);self.assertNotEqual(0,r.returncode);self.assertIn('foreign key',r.stderr.lower())
  for j in [one,two]:self.e.call('/import-jobs/'+j['id']+'/cancel','POST',{},j['rowVersion'])
  self.evidence.append({'postgresSkipLockedTwoConnections':'distinct claims','crossTenantTaskForeignKey':'rejected'})
 def test_09_reusedAttributesSevenTypesAndBearing(self):
  meta=self.e.call('/metadata','POST',{'kind':'ATTRIBUTE','code':TAG+'Quantity','data':{'type':'DECIMAL','unit':'mm','label':'复用尺寸','min':0}});ids=[]
  for suffix in ['A','B']:
   code=(TAG+suffix).upper();cat=self.e.call('/categories','POST',{'code':code,'name':'通用七类型验收'});attrs=[{'definitionId':meta['id'],'min':1,'required':True},{'code':'name','type':'STRING','required':True},{'code':'count','type':'INTEGER'},{'code':'flag','type':'BOOLEAN'},{'code':'date','type':'DATE'},{'code':'grade','type':'ENUM','options':[{'code':'X','label':'X','active':True}]},{'code':'ref','type':'REFERENCE','referenceType':'SUPPLIER'}];bundle={'attributes':attrs,'uiSchema':{'order':['name',TAG+'Quantity'],'fields':{'name':{'group':'基本'}}},'codeRule':{'segments':[{'type':'CONST','value':TAG+suffix},{'type':'ATTR','field':'name'}]},'samples':[{'attributes':{TAG+'Quantity':{'value':2,'unit':'mm'},'name':'TEST'},'valid':True}]};sc=self.e.call('/categories/'+code+'/schemas','POST',{'bundle':bundle});sc=self.e.call('/schemas/'+sc['id']+'/submit','POST',{},sc['rowVersion']);sc=self.r.call('/schemas/'+sc['id']+'/approve','POST',{},sc['rowVersion']);ids.append(sc['id']);values={TAG+'Quantity':{'value':1.270000,'unit':'m'},'name':'TEST','count':{'value':0},'flag':False,'date':'2026-10-06','grade':'X','ref':{'type':'SUPPLIER','id':'SUP-001'}};normalized=self.e.call('/materials:validate','POST',{'schemaVersionId':sc['id'],'materialName':'七类型','attributes':values});self.assertEqual(1270,normalized['attributes'][TAG+'Quantity']['value']);self.assertFalse(normalized['attributes']['flag']);self.e.call('/materials:validate','POST',{'schemaVersionId':sc['id'],'materialName':'错误日期','attributes':{**values,'date':'2026-02-30'}},expected=422);self.e.call('/materials:validate','POST',{'schemaVersionId':sc['id'],'materialName':'错误整数','attributes':{**values,'count':{'value':1.1}}},expected=422)
  self.e.call('/metadata/'+meta['id'],'PATCH',{'data':{**meta['data'],'type':'STRING'}},meta['rowVersion'],expected=409);self.assertEqual(meta['id'],self.e.call('/schemas/'+ids[1])['bundle']['attributes'][0]['definitionId']);s=self.e.call('/categories/BEARING/schema');body={'schemaVersionId':s['id'],'materialName':TAG+'轴承','attributes':{'innerDiameter':{'value':25,'unit':'mm'},'outerDiameter':{'value':52,'unit':'mm'},'bearingWidth':{'value':15,'unit':'mm'},'precision':'P0','seal':'2RS'}};preview=self.e.call('/material-numbers:preview','POST',body);self.assertTrue(preview['candidateMaterialNo'].startswith('BR-'));self.evidence.append({'reusedAttributeVersions':2,'sevenTypesAndInvalidDateInteger':'passed','bearingGenericConfiguration':'passed'})
 def test_10_identityRebindVersionsAndReplacement(self):
  ids=[]
  for i in range(2):
   body={'schemaVersionId':self.s['id'],'materialName':TAG+'关系'+str(i),'attributes':{'model':TAG+'REL'+str(i),'width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001'}}};m=self.e.call('/materials','POST',body,expected=201);r=self.e.call('/materials/'+m['id']+'/change-requests','POST',{'kind':'NEW'},m['rowVersion']);r=self.e.call('/requests/'+r['id']+'/submit','POST',{},r['rowVersion']);self.r.call('/requests/'+r['id']+'/approve','POST',{},r['rowVersion']);ids.append(m['id'])
  s=self.e.call('/integration-systems','POST',{'code':TAG+'BIND','name':'身份变更验证','config':{}});path='/integration-systems/'+s['id']+'/identities';i=self.e.call(path,'POST',{'externalId':TAG,'materialId':ids[0],'reason':'初始绑定'});j=self.e.call(path,'POST',{'externalId':TAG+'NEW','previousExternalId':TAG,'materialId':ids[0],'baseVersion':i['rowVersion'],'reason':'目标业务核实身份替换'});self.assertEqual(i['rowVersion']+1,j['rowVersion']);self.e.call(path,'POST',{'externalId':TAG+'OTHER','previousExternalId':TAG+'NEW','materialId':ids[0],'baseVersion':i['rowVersion'],'reason':'过期版本'},expected=409);self.e.call(path,'POST',{'externalId':TAG+'NEW','materialId':ids[1],'reason':'身份冲突'},expected=409);self.e.call('/materials/'+ids[0]+'/replacements','POST',{'replacementId':ids[1],'reason':'规格变更新建替代'});self.assertEqual(ids[1],self.e.call('/materials/'+ids[0])['replacements'][0]['replacementId']);self.evidence.append({'externalIdentityRebind':'version checked','replacementRelation':'persisted'})
 def test_11_fixedParsingAndStrictReferenceStructure(self):
  code=(TAG+'FIXED').upper();self.e.call('/categories','POST',{'code':code,'name':'固定段解析'});bundle={'attributes':[{'code':'name','type':'STRING','required':True}],'codeRule':{'segments':[{'type':'ATTR','field':'name'}]},'parseRule':{'kind':'FIXED','fields':{'name':{'start':0,'length':4}}},'samples':[{'attributes':{'name':'TEST'}}]};s=self.e.call('/categories/'+code+'/schemas','POST',{'bundle':bundle});s=self.e.call('/schemas/'+s['id']+'/submit','POST',{},s['rowVersion']);s=self.r.call('/schemas/'+s['id']+'/approve','POST',{},s['rowVersion']);p=self.e.call('/material-numbers:parse','POST',{'parseRuleVersionId':s['id'],'materialNo':'TEST'});self.assertEqual('EXACT_SYNTAX',p['matchType']);p=self.e.call('/material-numbers:parse','POST',{'parseRuleVersionId':s['id'],'materialNo':'TEST-extra'});self.assertEqual(['-extra'],p['unparsedSegments']);self.assertEqual('PARTIAL_SYNTAX',p['matchType']);self.e.call('/material-numbers:parse','POST',{'parseRuleVersionId':s['id'],'materialNo':'A'},expected=422)
  body={'schemaVersionId':self.s['id'],'materialName':'引用结构','attributes':{'model':TAG,'width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001','extra':'禁止静默丢弃'}}};r=self.e.call('/materials:validate','POST',body,expected=422);self.assertTrue(any(x['code']=='SCHEMA_STRUCTURE' for x in r['errors']));self.evidence.append({'fixedParser':'exact/partial/range checked','referenceUnknownField':'rejected by JSON Schema'})
 def test_12_categoryPoliciesAndErrorReport(self):
  cfg={'url':'http://localhost:9091/targets/'+TAG+'/materials','healthUrl':'http://localhost:9091/health','contractTestUrl':'http://localhost:9091/targets/'+TAG+'/validate'};s=self.e.call('/integration-systems','POST',{'code':TAG+'POLICY','name':'按类别归属策略','config':cfg});m=self.e.call('/integration-systems/'+s['id']+'/mappings','POST',{'config':{'fields':[{'source':'materialNo','target':'ITEM_CODE'}],'policiesByCategory':{'GLASS_CLOTH':{'attributes.description':'IGNORE'},'BEARING':{'attributes.description':'REVIEW'}}}});self.e.call('/mappings/'+m['id']+'/publish','POST',{},m['rowVersion']);self.e.call('/integration-systems/'+s['id']+'/test','POST',{});s=self.e.call('/integration-systems/'+s['id']);self.e.call('/integration-systems/'+s['id'],'PATCH',{'active':True},s['rowVersion']);glass={'model':TAG+'POLICY','width':{'value':1270,'unit':'mm'},'basisWeight':{'value':210,'unit':'g/m2'},'manufacturer':{'type':'SUPPLIER','id':'SUP-001'},'description':'字段归属'};bearing={'innerDiameter':{'value':25,'unit':'mm'},'outerDiameter':{'value':52,'unit':'mm'},'bearingWidth':{'value':15,'unit':'mm'},'precision':'P0','seal':'2RS','description':'字段归属'}
  results=[]
  for code,attrs in [('GLASS_CLOTH',glass),('BEARING',bearing)]:
   results.append(self.e.call('/integration-systems/'+s['id']+'/inbound','POST',{'sourceMessageId':TAG+code,'externalId':TAG+code,'categoryCode':code,'data':{'materialName':TAG+code,'attributes':attrs}}))
  self.assertIn('attributes.description',results[0]['ignoredFields']);self.assertIn('attributes.description',results[1]['reviewFields']);j=self.job(1);src=j['rows'][0]['source'];src['width']='-1';j=self.e.call('/import-jobs/'+j['id']+'/rows/1','PATCH',{'source':src},j['rows'][0]['rowVersion']);self.e.call('/import-jobs/'+j['id']+'/validate','POST',{},j['rowVersion']);j=self.wait(j,'READY');f=self.e.call('/import-jobs/'+j['id']+'/error-report','POST',{});raw=self.e.call('/files/'+f['id']);import csv
  report=list(csv.DictReader(io.StringIO(raw.decode('utf-8-sig'))));self.assertEqual('width',report[0]['sourceColumn']);self.assertEqual('/attributes/width',report[0]['targetAttribute']);self.assertEqual("'-1",report[0]['originalValue']);self.assertEqual('OUT_OF_RANGE',report[0]['errorCode']);self.assertTrue(report[0]['suggestion']);self.e.call('/import-jobs/'+j['id']+'/cancel','POST',{},j['rowVersion']);bad=upload(self.e,'/import-files',{'categoryCode':'GLASS_CLOTH'},'编码错误.csv',b'materialName\n\xff\n');self.e.call('/import-files/'+bad['fileId']+'/preview','POST',{'sheet':'CSV'},expected=422);self.evidence.append({'categoryFieldPolicies':'independent','errorReport':'source/target/code/original/suggestion','invalidUtf8':'rejected'})
 def test_13_importUpdateCategoryAndSchemaBinding(self):
  code=(TAG+'BINDING').upper();self.e.call('/categories','POST',{'code':code,'name':'导入版本绑定验证'});bundle={'attributes':[{'code':'name','type':'STRING'}],'codeRule':{'segments':[{'type':'CONST','value':code}]},'samples':[{'attributes':{'name':'A'}}]};versions=[]
  for _ in range(2):
   sc=self.e.call('/categories/'+code+'/schemas','POST',{'bundle':bundle});sc=self.e.call('/schemas/'+sc['id']+'/submit','POST',{},sc['rowVersion']);sc=self.r.call('/schemas/'+sc['id']+'/approve','POST',{},sc['rowVersion']);versions.append(sc)
  m=self.e.call('/materials','POST',{'schemaVersionId':versions[0]['id'],'materialName':TAG+'版本锁定','attributes':{'name':'A'}},expected=201);before=self.e.call('/materials/'+m['id']);mapping={k:k for k in ['id','baseVersion','materialName']};content=f"id,baseVersion,materialName\n{m['id']},{m['rowVersion']},不能跨类别或版本更新\n".encode()
  for category,sc,error in [('BEARING',self.e.call('/categories/BEARING/schema'),'SCHEMA_CATEGORY'),(code,versions[1],'SCHEMA_VERSION_CONFLICT')]:
   f=upload(self.e,'/import-files',{'categoryCode':category},'版本检查.csv',content);j=self.e.call('/import-jobs','POST',{'fileId':f['fileId'],'categoryCode':category,'schemaVersionId':sc['id'],'sheet':'CSV','mode':'UPDATE','mapping':mapping},expected=202);self.e.call('/import-jobs/'+j['id']+'/validate','POST',{},j['rowVersion']);j=self.wait(j,'READY');self.assertEqual('ERROR',j['rows'][0]['state']);self.assertEqual(error,j['rows'][0]['errors'][0]['code']);self.e.call('/import-jobs/'+j['id']+'/cancel','POST',{},j['rowVersion'])
  self.assertEqual(before,self.e.call('/materials/'+m['id']));self.evidence.append({'importUpdateCategoryAndSchemaMismatch':'rejected without material write'})
 @classmethod
 def tearDownClass(cls):
  p=pathlib.Path('.runtime/operations-evidence.json');old=json.loads(p.read_text()) if p.exists() else [];p.write_text(json.dumps(old+cls.evidence,ensure_ascii=False,indent=2))
if __name__=='__main__':unittest.main(verbosity=2)
