CREATE OR REPLACE FUNCTION guard_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN
  IF OLD.ever_published THEN RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_VERSION' USING ERRCODE='23514'; END IF;
  RETURN OLD;
 END IF;
 IF (NEW.id,NEW.tenant_id,NEW.category_id,NEW.code,NEW.version) IS DISTINCT FROM
    (OLD.id,OLD.tenant_id,OLD.category_id,OLD.code,OLD.version) THEN
  RAISE EXCEPTION 'IMMUTABLE_VERSION_KEY' USING ERRCODE='23514';
 END IF;
 IF TG_TABLE_NAME='config_version' THEN
  IF NEW.kind IS DISTINCT FROM OLD.kind THEN RAISE EXCEPTION 'IMMUTABLE_CONFIG_KIND' USING ERRCODE='23514'; END IF;
  IF OLD.status='REVIEW' AND NEW.definition IS DISTINCT FROM OLD.definition THEN
   RAISE EXCEPTION 'IMMUTABLE_REVIEW_CONFIG' USING ERRCODE='23514';
  END IF;
 END IF;
 IF OLD.ever_published THEN
  IF NOT NEW.ever_published OR NEW.status NOT IN ('PUBLISHED','RETIRED') THEN
   RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_VERSION' USING ERRCODE='23514';
  END IF;
  IF TG_TABLE_NAME='config_version' THEN
   IF NEW.definition IS DISTINCT FROM OLD.definition THEN
    RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_CONFIG' USING ERRCODE='23514';
   END IF;
  ELSE
   IF (NEW.refs,NEW.samples,NEW.dependency_snapshot,NEW.tests,NEW.submitted_by,NEW.approved_by,NEW.published_at)
    IS DISTINCT FROM (OLD.refs,OLD.samples,OLD.dependency_snapshot,OLD.tests,OLD.submitted_by,OLD.approved_by,OLD.published_at) THEN
    RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_RELEASE' USING ERRCODE='23514';
   END IF;
  END IF;
 END IF;
 RETURN NEW;
END $$;
