-- V3: ERP owns material facts. New tables contain metadata, ledger and non-authoritative snapshots.
ALTER TABLE tenant_member ADD COLUMN source_scope jsonb NOT NULL DEFAULT '["*"]';
CREATE TABLE source_system(id uuid PRIMARY KEY,tenant_id uuid REFERENCES tenant,code text NOT NULL,name text NOT NULL,type text NOT NULL CHECK(type IN('DATABASE','REST','INTERFACE_PLATFORM','FILE')),environment text NOT NULL DEFAULT 'DEV',status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','ACTIVE','SUSPENDED','RETIRED')),connection_profile jsonb NOT NULL,credential_hash text,owner_user_id uuid REFERENCES business_user,read_only boolean NOT NULL DEFAULT true,row_version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,code),UNIQUE(tenant_id,id));
CREATE TABLE source_object_version(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,source_system_id uuid NOT NULL,object_name text NOT NULL,schema_name text NOT NULL DEFAULT 'public',object_type text NOT NULL DEFAULT 'TABLE',version_no int NOT NULL,status text NOT NULL DEFAULT 'DRAFT',ever_published boolean NOT NULL DEFAULT false,structure_hash text NOT NULL,definition jsonb NOT NULL,import_method text NOT NULL,ddl_text text,created_at timestamptz NOT NULL DEFAULT now(),row_version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,source_system_id,schema_name,object_name,version_no),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id));
CREATE TABLE numbering_config(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenant,kind text NOT NULL CHECK(kind IN('DATASET','MAPPING','IDENTITY','CODE_RULE')),code text NOT NULL,version_no int NOT NULL,status text NOT NULL DEFAULT 'DRAFT',ever_published boolean NOT NULL DEFAULT false,source_system_id uuid,category_id uuid,definition jsonb NOT NULL,created_by uuid REFERENCES business_user,row_version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,kind,code,version_no),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,category_id) REFERENCES category(tenant_id,id));
CREATE TABLE release_package(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,code text NOT NULL,version_no int NOT NULL,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','REVIEW','PUBLISHED','RETIRED')),ever_published boolean NOT NULL DEFAULT false,source_system_id uuid NOT NULL,category_id uuid NOT NULL,dataset_id uuid NOT NULL,schema_id uuid NOT NULL,mapping_id uuid NOT NULL,identity_id uuid NOT NULL,code_rule_id uuid NOT NULL,definition jsonb NOT NULL,dependency_snapshot jsonb,tests jsonb,created_by uuid NOT NULL,submitted_by uuid,row_version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,code,version_no),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,category_id) REFERENCES category(tenant_id,id),FOREIGN KEY(tenant_id,dataset_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,schema_id) REFERENCES schema_version(tenant_id,id),FOREIGN KEY(tenant_id,mapping_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,identity_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,code_rule_id) REFERENCES numbering_config(tenant_id,id));
CREATE TABLE dataset_runtime(tenant_id uuid NOT NULL,dataset_code text NOT NULL,release_id uuid NOT NULL,actor uuid NOT NULL,enabled boolean NOT NULL DEFAULT false,interval_seconds int NOT NULL DEFAULT 60 CHECK(interval_seconds BETWEEN 1 AND 86400),next_scan_at timestamptz NOT NULL DEFAULT now(),cursor jsonb NOT NULL DEFAULT '{}',row_version bigint NOT NULL DEFAULT 1,PRIMARY KEY(tenant_id,dataset_code),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id));
CREATE TABLE scan_job(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,dataset_id uuid NOT NULL,release_id uuid NOT NULL,actor uuid NOT NULL,status text NOT NULL DEFAULT 'PENDING',trigger text NOT NULL,cursor_before jsonb NOT NULL DEFAULT '{}',cursor_after jsonb,scanned_count int NOT NULL DEFAULT 0,discovered_count int NOT NULL DEFAULT 0,skipped_count int NOT NULL DEFAULT 0,failed_count int NOT NULL DEFAULT 0,results jsonb NOT NULL DEFAULT '[]',started_at timestamptz,finished_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,dataset_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id));
CREATE TABLE processing_task(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,release_id uuid NOT NULL,scan_job_id uuid,source_record_key text NOT NULL,source_version text,status text NOT NULL DEFAULT 'DISCOVERED',error_code text,error_details jsonb NOT NULL DEFAULT '[]',assignment_id uuid,actor uuid NOT NULL,trace_id text,lease_until timestamptz,next_attempt_at timestamptz NOT NULL DEFAULT now(),attempts int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id),FOREIGN KEY(tenant_id,scan_job_id) REFERENCES scan_job(tenant_id,id));
CREATE TABLE material_assignment(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,source_system_id uuid NOT NULL,dataset_version_id uuid NOT NULL,dataset_code text NOT NULL,source_record_key text NOT NULL,generation_intent text NOT NULL DEFAULT 'INITIAL',category_id uuid NOT NULL,schema_version_id uuid NOT NULL,mapping_version_id uuid NOT NULL,identity_definition_version_id uuid NOT NULL,identity_canonical text NOT NULL,identity_hash text NOT NULL,code_rule_version_id uuid,release_id uuid NOT NULL,material_no varchar(128) NOT NULL,number_source text NOT NULL CHECK(number_source IN('GENERATED','LEGACY')),input_snapshot jsonb NOT NULL,source_version text,issue_request_id text NOT NULL,issued_at timestamptz NOT NULL DEFAULT now(),writeback_status text NOT NULL DEFAULT 'PENDING',erp_confirmed_at timestamptz,row_version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,material_no),UNIQUE(tenant_id,dataset_code,source_record_key),UNIQUE(tenant_id,category_id,identity_canonical),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,dataset_version_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,schema_version_id) REFERENCES schema_version(tenant_id,id),FOREIGN KEY(tenant_id,mapping_version_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,identity_definition_version_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,code_rule_version_id) REFERENCES numbering_config(tenant_id,id),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id),FOREIGN KEY(tenant_id,category_id) REFERENCES category(tenant_id,id));
CREATE INDEX assignment_identity_hash ON material_assignment(tenant_id,category_id,identity_hash);
CREATE INDEX assignment_source_lookup ON material_assignment(tenant_id,source_system_id,source_record_key);
CREATE INDEX assignment_issued_lookup ON material_assignment(tenant_id,issued_at,id);
ALTER TABLE processing_task ADD CONSTRAINT processing_assignment_tenant FOREIGN KEY(tenant_id,assignment_id) REFERENCES material_assignment(tenant_id,id);
CREATE TABLE material_source_snapshot(tenant_id uuid NOT NULL,source_system_id uuid NOT NULL,dataset_code text NOT NULL,source_record_key text NOT NULL,source_version text,release_id uuid NOT NULL,attributes jsonb NOT NULL,identity_canonical text,assignment_id uuid,copy_type text NOT NULL DEFAULT 'NON_AUTHORITATIVE_COPY' CHECK(copy_type='NON_AUTHORITATIVE_COPY'),observed_status text,last_read_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,source_system_id,dataset_code,source_record_key),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id),FOREIGN KEY(tenant_id,assignment_id) REFERENCES material_assignment(tenant_id,id));
CREATE TABLE writeback_task(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,assignment_id uuid NOT NULL,source_system_id uuid NOT NULL,actor uuid NOT NULL,state text NOT NULL DEFAULT 'PENDING' CHECK(state IN('PENDING','SENDING','WAIT_CONFIRMATION','RETRY_WAIT','RESULT_UNKNOWN','SUCCEEDED','FAILED')),adapter_snapshot jsonb NOT NULL,idempotency_key text NOT NULL,attempts int NOT NULL DEFAULT 0,revision int NOT NULL DEFAULT 0,parent_id uuid,error_code text,error_details jsonb,lease_until timestamptz,next_attempt_at timestamptz NOT NULL DEFAULT now(),confirmed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,assignment_id,revision),FOREIGN KEY(tenant_id,assignment_id) REFERENCES material_assignment(tenant_id,id),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,parent_id) REFERENCES writeback_task(tenant_id,id));
CREATE INDEX writeback_due ON writeback_task(state,next_attempt_at);
CREATE TABLE writeback_attempt(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,task_id uuid NOT NULL,attempt int NOT NULL,phase text NOT NULL,http_status int,result jsonb,error_code text,trace_id text,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,task_id) REFERENCES writeback_task(tenant_id,id));
CREATE TABLE numbering_outbox(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,assignment_id uuid NOT NULL,task_id uuid NOT NULL,event_type text NOT NULL DEFAULT 'NUMBER_ISSUED',snapshot jsonb NOT NULL,trace_id text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,assignment_id),FOREIGN KEY(tenant_id,assignment_id) REFERENCES material_assignment(tenant_id,id),FOREIGN KEY(tenant_id,task_id) REFERENCES writeback_task(tenant_id,id));
CREATE TABLE numbering_reconciliation(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,source_system_id uuid NOT NULL,release_id uuid NOT NULL,actor uuid NOT NULL,status text NOT NULL,results jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,source_system_id) REFERENCES source_system(tenant_id,id),FOREIGN KEY(tenant_id,release_id) REFERENCES release_package(tenant_id,id));
CREATE FUNCTION guard_v3_versions() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN IF OLD.ever_published THEN RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_CONFIGURATION'; END IF; RETURN OLD; END IF;
 IF OLD.ever_published AND (NEW.definition IS DISTINCT FROM OLD.definition OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id OR NEW.id IS DISTINCT FROM OLD.id OR NEW.ever_published=false) THEN RAISE EXCEPTION 'IMMUTABLE_PUBLISHED_CONFIGURATION'; END IF;
 IF TG_TABLE_NAME='release_package' AND OLD.ever_published AND (NEW.dataset_id IS DISTINCT FROM OLD.dataset_id OR NEW.schema_id IS DISTINCT FROM OLD.schema_id OR NEW.mapping_id IS DISTINCT FROM OLD.mapping_id OR NEW.identity_id IS DISTINCT FROM OLD.identity_id OR NEW.code_rule_id IS DISTINCT FROM OLD.code_rule_id OR NEW.dependency_snapshot IS DISTINCT FROM OLD.dependency_snapshot) THEN RAISE EXCEPTION 'IMMUTABLE_RELEASE_DEPENDENCIES'; END IF;
 RETURN NEW; END; $$;
CREATE TRIGGER object_v3_immutable BEFORE UPDATE OR DELETE ON source_object_version FOR EACH ROW EXECUTE FUNCTION guard_v3_versions();
CREATE TRIGGER config_v3_immutable BEFORE UPDATE OR DELETE ON numbering_config FOR EACH ROW EXECUTE FUNCTION guard_v3_versions();
CREATE TRIGGER release_v3_immutable BEFORE UPDATE OR DELETE ON release_package FOR EACH ROW EXECUTE FUNCTION guard_v3_versions();
CREATE FUNCTION guard_assignment_ledger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'ASSIGNMENT_CANNOT_BE_DELETED'; END IF;
 IF (to_jsonb(NEW)-'writeback_status'-'erp_confirmed_at'-'row_version') IS DISTINCT FROM (to_jsonb(OLD)-'writeback_status'-'erp_confirmed_at'-'row_version') THEN RAISE EXCEPTION 'IMMUTABLE_ASSIGNMENT_LEDGER'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER ledger_immutable BEFORE UPDATE OR DELETE ON material_assignment FOR EACH ROW EXECUTE FUNCTION guard_assignment_ledger();
-- Extend existing roles, preserving their existing action grants.
UPDATE role SET actions=actions || '["SOURCE_READ"]'::jsonb;
UPDATE role SET actions=actions || '["SOURCE_EDIT","SOURCE_IMPORT","DATASET_DESIGN","MAPPING_DESIGN","IDENTITY_DESIGN","RULE_DESIGN"]'::jsonb WHERE code IN('ADMIN','DESIGNER');
UPDATE role SET actions=actions || '["SCAN","ASSIGN","WRITEBACK","RECONCILE"]'::jsonb WHERE code='INTEGRATOR';
