import { test, expect } from '@playwright/test';
const login=async(page:any,user='editor')=>{await page.goto('/');await page.locator('form select').selectOption(user);await page.getByRole('button',{name:/进入工作台/}).click();await expect(page.locator('.sidebar')).toBeVisible();await expect(page.locator('.loading-line')).toHaveCount(0);};
test('V4 工作台、三类别预览和可解释账本',async({page})=>{
 await login(page);
 await expect(page.locator('.stat-grid article')).toHaveCount(4);
 await expect(page.locator('.category-cards article')).toHaveCount(3);
 await expect(page.locator('nav')).not.toContainText(/扫描|写回|Dataset|对账/);
 await page.getByRole('button',{name:'05 发号预览'}).click();
 await page.getByRole('button',{name:/运行预览/}).click();
 await expect(page.getByTestId('material-no')).toHaveText('GC-7628-A-210-1270-HH');
 await expect(page.locator('main')).toContainText('Material Identity');
 await expect(page.locator('main')).toContainText('basisWeight');
 await page.getByLabel('预览类别').selectOption('BEARING');
 await page.getByRole('button',{name:/运行预览/}).click();
 await expect(page.getByTestId('material-no')).toHaveText('BR-DEEP_GROOVE-25-52-15-2RS-SKF');
 await page.getByLabel('预览类别').selectOption('RESISTOR');
 await page.getByRole('button',{name:/运行预览/}).click();
 await expect(page.getByTestId('material-no')).toHaveText('EC-0603-{SEQUENCE:MAIN:6}');
 await expect(page.locator('main')).toContainText('流水占位符 · 未占号');
 await page.screenshot({path:'../.runtime/v4-preview.png',fullPage:true});
 await page.getByRole('button',{name:'07 发号账本'}).click();
 await page.getByLabel('企业料号',{exact:true}).fill('GC-7628-A-210-1270-HH');
 await page.getByRole('button',{name:'查询账本'}).click();
 await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'查看解释 →'}).click();
 await expect(page.locator('.explanation')).toContainText('Raw Input');
 await expect(page.locator('.explanation')).toContainText('GC-7628-A-210-1270-HH');
});
test('调用系统注册、类别授权、凭据轮换与暂停',async({page})=>{
 await login(page);
 await page.getByRole('button',{name:'02 调用系统'}).click();
 const code='BROWSER_'+Date.now();
 await page.getByLabel('系统代码').fill(code);await page.getByLabel('系统名称').fill('浏览器调用方');
 await page.getByLabel('允许类别').selectOption(['GLASS_CLOTH']);
 await page.getByRole('button',{name:'注册并生成凭据'}).click();
 await expect(page.locator('.key-reveal code')).toBeVisible();
 const key=await page.locator('.key-reveal code').innerText();expect(key.length).toBeGreaterThan(40);
 const row=page.locator('tbody tr').filter({hasText:code});
 await row.getByRole('button',{name:'暂停',exact:true}).click();await expect(row).toContainText('已暂停');
 await row.getByRole('button',{name:'启用',exact:true}).click();await expect(row).toContainText('已启用');
 await row.getByRole('button',{name:'轮换凭据'}).click();
 await expect(page.locator('.key-reveal code')).not.toHaveText(key);
});
test('配置新版本、回归测试和双人发布',async({page})=>{
 await login(page,'admin');
 await page.getByRole('button',{name:'04 身份与编码规则'}).click();
 await page.getByLabel('配置类型').selectOption('code-rules');
 const versions=page.locator('tbody tr').filter({hasText:'GLASS_CLOTH_CODE_RULES'});
 await expect(versions.first()).toBeVisible();
 const before=await versions.count();
 const row=versions.first();
 await row.getByRole('button',{name:'打开配置'}).click();
 await page.getByRole('button',{name:'保存为新版本'}).click();
 await expect(versions).toHaveCount(before+1);
 await page.getByRole('button',{name:'06 发布与审批'}).click();
 await page.getByRole('button',{name:'＋ 新建发布包'}).click();
 await page.getByRole('button',{name:'保存发布包草稿'}).click();
 const release=page.locator('tbody tr').filter({hasText:'GLASS_CLOTH_RELEASE'}).first();
 await release.getByRole('button',{name:'测试',exact:true}).click();await expect(release).toContainText('通过');
 await release.getByRole('button',{name:'提交审批'}).click();await expect(release).toContainText('待审批');
 await release.getByRole('button',{name:'审批并发布'}).click();
 await expect(page.getByRole('alert')).toContainText('SEPARATION_OF_DUTIES');
 await page.getByRole('button',{name:'退出',exact:true}).click();await login(page,'reviewer');
 await page.getByRole('button',{name:'06 发布与审批'}).click();
 const pending=page.locator('tbody tr').filter({hasText:'GLASS_CLOTH_RELEASE'}).filter({hasText:'待审批'});
 await pending.getByRole('button',{name:'审批并发布'}).click();
 await expect(page.locator('tbody tr').filter({hasText:'GLASS_CLOTH_RELEASE'}).filter({hasText:'已发布'})).toHaveCount(1);
});
test('只读角色隔离、租户切换和移动布局',async({page})=>{
 await login(page,'reader');
 await expect(page.locator('nav')).not.toContainText('调用系统');
 await expect(page.locator('nav')).not.toContainText('审计日志');
 await page.getByRole('button',{name:'07 发号账本'}).click();
 await page.getByLabel('当前租户').selectOption('TENANT-B');
 await expect(page.locator('main')).toContainText('没有符合条件的发号记录');
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('main')).toBeVisible();
 const widths=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));
 expect(widths.scroll).toBeLessThanOrEqual(widths.client+1);
});
